### PR TITLE
feat: add AP-11 Diagnosing a problem in production at the pod level

### PR DESCRIPTION
**Pull request by pmuir**

### CODE REVIEW

**Comment by pmuir** [comment]
@emmanuelbernard I'm not convinced this is an architectural pattern. I think it's a howto - in which case it could be a blog or similar.

**Comment by emmanuelbernard** [comment]
@StevenTobin can you see how we can convert this one into a SOP even though not actionable from a defined root cause yet? Would you agree.
We can also see how we would also blog it for exchange, @maxandersen fancy doing a blog around it?

**Comment by emmanuelbernard** [comment]
@StevenTobin to see if the generic SPO can be improved with that content.

**Comment by emmanuelbernard** [comment]
Closing as not able to find the content a productive home.

**Pull request closed without merging**
